name: Backend Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  pull_request:
      paths:
      - backend/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Test with pytest
      env:
        FLASK_SECRET_KEY: "test_secret_key"
      run: |
        cd backend
        python db/db.py
        pytest
